apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  validation: client
  # we supply an inline patch for the deployment
  # patchesJson6902:
  #   - target:
  #       version: apps/v1
  #       kind: Deployment
  #       name: podinfo
  #     patch:
  #     - op: add
  #       path: /metadata/labels/scheduler
  #       value: fargate
  #     - op: add
  #       path: /spec/template/metadata/labels/scheduler
  #       value: fargate
  patchesStrategicMerge:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: podinfo
        labels:
          scheduler: fargate
      spec:
        replicas: 3
        template:
          metadata:
            labels:
              scheduler: fargate
    - apiVersion: v1
      kind: Service
      metadata:
        name: podinfo
      spec:
        type: LoadBalancer